import base64
import asyncio
from google import genai
from app.config.settings import settings
from app.core.logger import logger
from app.services.firebase_storage import upload_image

client = genai.Client(api_key=settings.GEMINI_API_KEY)

MAX_IMAGE_RETRIES = 3
RETRY_DELAYS_SECONDS = (2, 4, 6)

async def generate_scene_image(prompt: str):
    """
    Generates an image for a story scene using Google's Imagen model.
    Uploads to Firebase for persistence and returns both inline data and the storage URL.
    """
    if not settings.ENABLE_IMAGE_GENERATION:
        logger.info("Image generation disabled. Returning placeholder asset instead of calling Imagen.")
        return {
            "inline_data": settings.IMAGE_PLACEHOLDER_PATH,
            "storage_url": settings.IMAGE_PLACEHOLDER_PATH,
        }

    logger.info(f"Generating image for prompt: {prompt[:50]}...")

    for attempt in range(1, MAX_IMAGE_RETRIES + 1):
        try:
            response = await asyncio.to_thread(
                client.models.generate_images,
                model=settings.IMAGE_MODEL_NAME,
                prompt=prompt,
                config={
                    "number_of_images": 1,
                }
            )

            if response.generated_images:
                image_bytes = response.generated_images[0].image.image_bytes

                # Keep the Firebase upload for persistence, but do not depend on it for frontend access.
                image_url = await asyncio.to_thread(upload_image, image_bytes)
                if image_url:
                    logger.info(f"Image uploaded successfully: {image_url}")
                else:
                    logger.warning("Failed to upload image to Firebase. Returning inline image data instead.")

                image_base64 = base64.b64encode(image_bytes).decode("utf-8")
                return {
                    "inline_data": f"data:image/png;base64,{image_base64}",
                    "storage_url": image_url,
                }

            logger.warning(f"No image generated by Imagen on attempt {attempt}.")
        except Exception as e:
            logger.warning("Image generation attempt %s failed: %s", attempt, str(e), exc_info=True)

        if attempt < MAX_IMAGE_RETRIES:
            delay = RETRY_DELAYS_SECONDS[min(attempt - 1, len(RETRY_DELAYS_SECONDS) - 1)]
            logger.info(f"Retrying image generation in {delay} seconds...")
            await asyncio.sleep(delay)

    logger.error("Image generation failed after all retry attempts.")
    return None
