import base64
from google import genai
from app.config.settings import settings
from app.core.logger import logger
from app.services.firebase_storage import upload_image

client = genai.Client(api_key=settings.GEMINI_API_KEY)

def generate_scene_image(prompt: str):
    """
    Generates an image for a story scene using Google's Imagen model.
    Uploads to Firebase and returns the public URL.
    """
    try:
        logger.info(f"Generating image for prompt: {prompt[:50]}...")
        
        response = client.models.generate_images(
            model=settings.IMAGE_MODEL_NAME,
            prompt=prompt,
            config={
                "number_of_images": 1,
            }
        )
        
        if response.generated_images:
            image_bytes = response.generated_images[0].image.image_bytes
            
            # Upload to Firebase Storage
            image_url = upload_image(image_bytes)
            
            if image_url:
                logger.info(f"Image uploaded successfully: {image_url}")
                return image_url
            else:
                logger.error("Failed to upload image to Firebase.")
                return None
        
        logger.warning("No image generated by Imagen.")
        return None

    except Exception as e:
        logger.error(f"Error generating or uploading image: {str(e)}")
        return None
